services:
    website-production:
        container_name: indonesian-emergency-sound-classification-website-production

        build:
            context: ./website
            target: production
            args:
                NEXT_PUBLIC_CLASSIFICATION_URL: ${NEXT_PUBLIC_WEBSITE_CLASSIFICATION_URL}

        env_file:
            - .env

        environment:
            - PORT=${WEBSITE_PORT}
            - NEXT_PUBLIC_CLASSIFICATION_URL=${NEXT_PUBLIC_WEBSITE_CLASSIFICATION_URL}

        restart: always

        expose:
            - ${WEBSITE_PORT}

        networks:
            - app-network

    server-production:
        container_name: indonesian-emergency-sound-classification-server-production

        build:
            context: ./server
            target: production
            args:
                - MODEL_URL=${MODEL_URL}

        env_file:
            - .env

        environment:
            - PORT=${SERVER_PORT}

        restart: always

        expose:
            - ${SERVER_PORT}

        networks:
            - app-network

networks:
    app-network:
        name: app-network
        driver: bridge
        external: true
