services:
    website-production:
        container_name: indonesian-emergency-sound-classification-website-production

        build:
            context: ./website
            target: production
            args:
                NEXT_PUBLIC_CLASSIFICATION_URL: ${NEXT_PUBLIC_WEBSITE_CLASSIFICATION_URL}

        env_file:
            - .env

        environment:
            - PORT=${WEBSITE_PORT}
            - NEXT_PUBLIC_CLASSIFICATION_URL=${NEXT_PUBLIC_WEBSITE_CLASSIFICATION_URL}

        restart: always

        networks:
            - default
        
        labels:
        - "traefik.http.services.website-production.loadbalancer.server.port=3000"
  

    server-production:
        container_name: indonesian-emergency-sound-classification-server-production

        build:
            context: ./server
            target: production
            args:
                - MODEL_URL=${MODEL_URL}

        env_file:
            - .env

        environment:
            - PORT=${SERVER_PORT}

        restart: always

        networks:
            - default

        labels:
            - "traefik.http.services.server-production.loadbalancer.server.port=3001"

networks:
    default:
        driver: bridge
